apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway-ingress-admin
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - path: /admin(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: feedback-api-service
                port:
                  number: 9000
