apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedback-api
  labels:
    system: primary
    app: feedback-api
  namespace: default
spec:
  selector:
    matchLabels:
      system: primary
      app: feedback-api
  replicas: 2
  template:
    metadata:
      labels:
        system: primary
        app: feedback-api
    spec:
      containers:
        - image: localregistry.lc:30500/feedback-api
          imagePullPolicy: Always
          name: feedback-api
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: DATABASE_DIR
              value: /usr/db
          volumeMounts:
            - name: sqlite-volume
              mountPath: /usr/db
      volumes:
        - name: sqlite-volume
          persistentVolumeClaim:
            claimName: sqlite-pvc
      nodeSelector:
        system: node-1
      livenessProbe:
        httpGet:
          path: /health
          port: 8080
        initialDelaySeconds: 3
        periodSeconds: 3

---
apiVersion: v1
kind: Service
metadata:
  name: feedback-api
spec:
  selector:
    app: feedback-api
    system: primary
  ports:
    - port: 8080
