apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedback-api
  labels:
    app: feedback-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: feedback-api
  template:
    metadata:
      labels:
        app: feedback-api
    spec:
      containers:
        - name: feedback-api
          image: localregistry.lc:30500/feedback-api:submission
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
              protocol: TCP
          env:
            - name: DATABASE_DIR
              value: /usr/db
          volumeMounts:
            - name: sqlite-volume
              mountPath: /usr/db
          livenessProbe:
            httpGet:
              path: /health
              port: 9000
            initialDelaySeconds: 3
            periodSeconds: 3
      volumes:
        - name: sqlite-volume
          persistentVolumeClaim:
            claimName: sqlite-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqlite-pv
  labels:
    volume: sqlite
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/db"
