apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedback-api-deployment
  labels:
    app: feedback-api-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: feedback-api
  replicas: 2
  template:
    metadata:
      labels:
        app: feedback-api
    spec:
      containers:
        - image: localregistry.lc:30500/feedback-api:submission
          imagePullPolicy: Always
          name: feedback-api
          ports:
            - containerPort: 9000
              protocol: TCP
          env:
            - name: DATABASE_DIR
              value: /usr/db
          volumeMounts:
            - name: sqlite-volume
              mountPath: /usr/db
          livenessProbe:
            httpGet:
              path: /health
              port: 9000
            initialDelaySeconds: 3
            periodSeconds: 3
      volumes:
        - name: sqlite-volume
          persistentVolumeClaim:
            claimName: sqlite-pvc
