apiVersion: apps/v1
kind: Deployment
metadata:
  name: logic-api-deployment
  labels:
    app: logic-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: logic-api
  template:
    metadata:
      labels:
        app: logic-api
    spec:
      containers:
        - image: localregistry.lc:30500/logic-api:submission
          imagePullPolicy: Always
          name: logic-api
          ports:
            - containerPort: 5000
